In [1]:
import numpy as np
import random

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
vector = np.array([random.uniform(0,1) for x in range(10)])
vector

array([0.39369376, 0.28225159, 0.82773129, 0.71698178, 0.82389798,
       0.9656721 , 0.91357395, 0.24572082, 0.44222743, 0.47238872])

In [3]:
vector = np.random.rand(10)
vector

array([0.83543099, 0.68946332, 0.62349972, 0.67698549, 0.74449871,
       0.33930173, 0.3738103 , 0.16660233, 0.1819922 , 0.53788483])

In [4]:
matrix = np.arange(11, 38, 3).reshape(3,3)
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [5]:
vector_plus_10 = np.round(vector + 10, 2)
vector_plus_10

array([10.84, 10.69, 10.62, 10.68, 10.74, 10.34, 10.37, 10.17, 10.18,
       10.54])

In [6]:
matrix_x2 = matrix * 2
matrix_x2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [7]:
vector_power_2 = vector ** 2
vector_power_2

array([0.69794494, 0.47535967, 0.3887519 , 0.45830935, 0.55427833,
       0.11512566, 0.13973414, 0.02775634, 0.03312116, 0.28932009])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [11]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [14]:
result_matrix.shape

(2, 2)

При множені матриці `result_matrix`,з розмірністю 2х2, на матрицю `С` з розмірністю 2х1 ми отримаємо матрицю 2х1 з діагоналю матриці `result_matrix` від правого верхнього кута до лівого нижнього


In [12]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [16]:
np.dot(result_matrix, C).shape

(2, 1)

При множені матриці `result_matrix`,з розмірністю 2х2, на матрицю `D` з розмірністю 2х2 ми отримаємо матрицю 2х2 де діагоналі матриці `result_matrix` змінені місцями

In [18]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])

In [17]:
np.dot(result_matrix, D).shape

(2, 2)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [19]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [25]:
vector

array([0.83543099, 0.68946332, 0.62349972, 0.67698549, 0.74449871,
       0.33930173, 0.3738103 , 0.16660233, 0.1819922 , 0.53788483])

In [21]:
vector.T

array([0.83543099, 0.68946332, 0.62349972, 0.67698549, 0.74449871,
       0.33930173, 0.3738103 , 0.16660233, 0.1819922 , 0.53788483])

In [24]:
vector.shape, vector.T.shape

((10,), (10,))

Після транспонування вектора `column_vector` змін ні в структурі ні за розмірністю не спостерігаю

In [27]:
column_vector = np.expand_dims(vector, axis = 1)
column_vector

array([[0.83543099],
       [0.68946332],
       [0.62349972],
       [0.67698549],
       [0.74449871],
       [0.33930173],
       [0.3738103 ],
       [0.16660233],
       [0.1819922 ],
       [0.53788483]])

In [28]:
column_vector.shape

(10, 1)

In [29]:
column_vector.T

array([[0.83543099, 0.68946332, 0.62349972, 0.67698549, 0.74449871,
        0.33930173, 0.3738103 , 0.16660233, 0.1819922 , 0.53788483]])

In [30]:
column_vector.T.shape

(1, 10)

Змінна `column_vector` має структуру і розмірність, що відповідає матриці 10х1. Відповідно, після транспонування маємо розмірність 1х10